"""empty message

Revision ID: 1022bcf63595
Revises: 
Create Date: 2023-01-14 13:27:27.716486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1022bcf63595'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reading', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evc', sa.String(length=8), nullable=False),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('topup_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evc')
    )
    op.create_table('meter_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('electricity_day', sa.Float(), nullable=False),
    sa.Column('electricity_night', sa.Float(), nullable=False),
    sa.Column('gas', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tariff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_name', sa.String(length=100), nullable=False),
    sa.Column('electricity_day_per_kWh', sa.Float(), nullable=False),
    sa.Column('electricity_night_per_kWh', sa.Float(), nullable=False),
    sa.Column('gas_per_kWh', sa.Float(), nullable=False),
    sa.Column('standing_charge_per_day', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tariff_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('num_bedrooms', sa.Integer(), nullable=True),
    sa.Column('evc', sa.Integer(), nullable=True),
    sa.Column('energy_credit', sa.Float(), nullable=True),
    sa.Column('joined_on', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['evc'], ['evc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('electricity_day_reading', sa.Float(), nullable=False),
    sa.Column('electricity_night_reading', sa.Float(), nullable=False),
    sa.Column('gas_reading', sa.Float(), nullable=False),
    sa.Column('bill_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill')
    op.drop_table('admin')
    op.drop_table('users')
    op.drop_table('tariff')
    op.drop_table('meter_reading')
    op.drop_table('evc')
    op.drop_table('energy_consumption')
    # ### end Alembic commands ###
