"""empty message

Revision ID: 422a25b01c6a
Revises: 4a2ad816f7db
Create Date: 2023-01-14 00:47:30.211077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '422a25b01c6a'
down_revision = '4a2ad816f7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tariff_name', sa.String(length=100), nullable=False))
        batch_op.alter_column('electricity_day_per_kWh',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('electricity_night_per_kWh',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('gas_per_kWh',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('standing_charge_per_day',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['tariff_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariff', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('standing_charge_per_day',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('gas_per_kWh',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('electricity_night_per_kWh',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('electricity_day_per_kWh',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_column('tariff_name')

    # ### end Alembic commands ###
