"""empty message

Revision ID: 607952efb387
Revises: 1022bcf63595
Create Date: 2023-01-14 14:07:36.338204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607952efb387'
down_revision = '1022bcf63595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meter_reading', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meter_reading', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
